#!/bin/bash
rm -f x.tex
find . -name '*.log' -type f -delete
find . -name '*.aux' -type f -delete
find . -name '*.toc' -type f -delete
find . -name '*.lot' -type f -delete
find . -name '*.lof' -type f -delete
find . -name '*.bbl' -type f -delete
find . -name '*.blg' -type f -delete
find . -name '*.out' -type f -delete
find . -name '*.glg' -type f -delete
find . -name '*.glo' -type f -delete
find . -name '*.gls' -type f -delete
find . -name '*.ist' -type f -delete
